/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemavuelos;
import javax.swing.JPanel;
/**
 *
 * @author israe
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    Aerolinea an=new Aerolinea("Nacional");
    Aerolinea ai=new Aerolinea("Internacional");   
    private Boolean bolea=false;
    
    public void GenerarDatos(){
      
        an.AnadirVuelo("Nacional",60, "18 de marzo","19 de marzo","001N","Guayaquil","Quito");
        an.AnadirVuelo("Nacional",60, "20 de marzo","26 de marzo","002N","Quito","Guayaquil");
        an.AnadirVuelo("Nacional",200, "24 de marzo","28 de marzo","003N","Galapagos","Quito");
        an.AnadirVuelo("Nacional",100, "28 de marzo","30 de marzo","004N","Cuenca","Guayaquil");       
                  
        ai.AnadirVuelo("Internacional",590, "18 de marzo","19 de marzo","001I","Madrid-España","Ecuador");
        ai.AnadirVuelo("Internacional",490, "20 de marzo","26 de marzo","002I","Los Angeles-Estados Unidos","Ecuador");
        ai.AnadirVuelo("Internacional",900, "24 de marzo","28 de marzo","003I","Tokyo-Japon","Ecuador");
        ai.AnadirVuelo("Internacional",500, "28 de marzo","30 de marzo","004I","Rio de Janeiro-Brasil","Ecuador");
    }
    private void CambiarPanel(JPanel p){
        p.setLocation(0,0);
        grupo.removeAll();
        grupo.add(p);
        grupo.revalidate();
        grupo.repaint();
    }
 
    public ventana() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane10 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        grupo = new javax.swing.JLayeredPane();
        Menu = new javax.swing.JPanel();
        todos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nacionalB = new javax.swing.JButton();
        internacionalB = new javax.swing.JButton();
        buscarT = new javax.swing.JTextField();
        buscarB = new javax.swing.JButton();
        VerBoleto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        VInternacionales = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        RegresarVI = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Madrid = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Tokyio = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LosAngeles = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        RioDeJaneiro = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Boleto = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        BoletoVer = new javax.swing.JTextArea();
        BoletoMenu = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        VNacionales = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        regresarVN = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Guayaquil = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Quito = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Galapagos = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Cuenca = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Vuelos = new javax.swing.JPanel();
        NGuayaquil = new javax.swing.JButton();
        ResG = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaGua = new javax.swing.JTextArea();
        ResQ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaEs = new javax.swing.JTextArea();
        NQuito = new javax.swing.JButton();
        NGalapagos = new javax.swing.JButton();
        ResBra = new javax.swing.JButton();
        ResCu = new javax.swing.JButton();
        ResEs = new javax.swing.JButton();
        ResEe = new javax.swing.JButton();
        ResJa = new javax.swing.JButton();
        regresarVT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaCu = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        AreaQui = new javax.swing.JTextArea();
        NCuenca = new javax.swing.JButton();
        IMadrid = new javax.swing.JButton();
        ILosAngeles = new javax.swing.JButton();
        IJapon = new javax.swing.JButton();
        Brasil = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        AreaGa = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        AreaBra = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        AreaJa = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        AreaEE = new javax.swing.JTextArea();
        ResGa = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        BusquedaF = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        BusquedaE = new javax.swing.JPanel();
        regresarBE = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TextoEncontrado = new javax.swing.JTextArea();
        ReservarBE = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Reservar = new javax.swing.JPanel();
        Nombre = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nacionalidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Genero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ReservarRegresar = new javax.swing.JButton();
        ReservarConfirmar = new javax.swing.JButton();

        jScrollPane10.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        grupo.setLayout(new java.awt.CardLayout());

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setPreferredSize(new java.awt.Dimension(800, 500));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avionNARANJA (1).jpg"))); // NOI18N
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });
        Menu.add(todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 40, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha (1).png"))); // NOI18N
        jLabel12.setText("jLabel11");
        jLabel12.setToolTipText("");
        Menu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha (1).png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setToolTipText("");
        Menu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 30, 30));

        nacionalB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        nacionalB.setText("Vuelos nacionales");
        nacionalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalBActionPerformed(evt);
            }
        });
        Menu.add(nacionalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 160, 30));

        internacionalB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        internacionalB.setText("Vuelos internacionales");
        internacionalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internacionalBActionPerformed(evt);
            }
        });
        Menu.add(internacionalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 160, 30));

        buscarT.setForeground(new java.awt.Color(102, 102, 102));
        buscarT.setText("Descubra su vuelo...");
        buscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTActionPerformed(evt);
            }
        });
        Menu.add(buscarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 410, -1));

        buscarB.setForeground(new java.awt.Color(255, 255, 255));
        buscarB.setToolTipText("Buscar");
        buscarB.setBorderPainted(false);
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });
        Menu.add(buscarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 40, 30));

        VerBoleto.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        VerBoleto.setText("Ver Boleto");
        VerBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerBoletoActionPerformed(evt);
            }
        });
        Menu.add(VerBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 130, 30));

        jPanel1.setBackground(new java.awt.Color(7, 43, 142));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Encuentra tu vuelo...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(23, 23, 23))
        );

        Menu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mio100.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        Menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 300, 400));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jLabel10.setText("Vuelos");
        Menu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 50, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/otracampaña (1).png"))); // NOI18N
        jLabel13.setText("jLabel13");
        Menu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 190, 100));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CampañaViajesOk (1).jpg"))); // NOI18N
        jLabel14.setText("jLabel13");
        Menu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 190, 100));

        grupo.add(Menu, "card2");

        VInternacionales.setBackground(new java.awt.Color(204, 204, 204));
        VInternacionales.setPreferredSize(new java.awt.Dimension(800, 500));
        VInternacionales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 47, 142));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ofertas de viaje - Internacionales");

        RegresarVI.setText("Regresar");
        RegresarVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarVIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(RegresarVI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(RegresarVI))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        VInternacionales.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        Madrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gran-via-Madrid (1).jpg"))); // NOI18N
        Madrid.setText("Madrid-España");
        Madrid.setBorderPainted(false);
        Madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MadridActionPerformed(evt);
            }
        });

        jLabel17.setText("USD");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("jLabel16");

        jLabel19.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel19.setText("Madrid -España");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Madrid, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        VInternacionales.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 160));

        Tokyio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tokio (1).jpg"))); // NOI18N
        Tokyio.setText("Tokyio - Japon");
        Tokyio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TokyioActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel16.setText("Tokio - Japón");

        jLabel20.setText("USD");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("jLabel16");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(Tokyio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Tokyio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addContainerGap())))
        );

        VInternacionales.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, -1));

        LosAngeles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/angeles (1).jpg"))); // NOI18N
        LosAngeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LosAngelesActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel22.setText("Los Angeles - EEUU");

        jLabel23.setText("USD");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("jLabel16");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(LosAngeles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(LosAngeles, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );

        VInternacionales.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        RioDeJaneiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rio-de-Janeiro-2020 (1).jpg"))); // NOI18N
        RioDeJaneiro.setText("Rio de Janeiro - Brasil");
        RioDeJaneiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RioDeJaneiroActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel25.setText("Rio de Janeiro - Brasil");

        jLabel26.setText("USD");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("jLabel16");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(RioDeJaneiro, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(RioDeJaneiro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addContainerGap())))
        );

        VInternacionales.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 202, -1));

        grupo.add(VInternacionales, "card4");

        Boleto.setPreferredSize(new java.awt.Dimension(800, 500));
        Boleto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BoletoVer.setEditable(false);
        BoletoVer.setColumns(20);
        BoletoVer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BoletoVer.setRows(5);
        jScrollPane11.setViewportView(BoletoVer);

        Boleto.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 400, 270));

        BoletoMenu.setText("Menu");
        BoletoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoletoMenuActionPerformed(evt);
            }
        });
        Boleto.add(BoletoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jPanel13.setBackground(new java.awt.Color(0, 46, 140));

        jLabel1.setFont(new java.awt.Font("ISOCPEUR", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Su Boleto");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        Boleto.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        jLabel42.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel42.setText("Detalles:");
        Boleto.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        grupo.add(Boleto, "card6");

        VNacionales.setBackground(new java.awt.Color(204, 204, 204));
        VNacionales.setPreferredSize(new java.awt.Dimension(800, 500));
        VNacionales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 46, 140));

        regresarVN.setText("Regresar");
        regresarVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarVNActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Ofertas de viaje - Nacionales");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(regresarVN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarVN)
                    .addComponent(jLabel40))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        VNacionales.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        Guayaquil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guayaquil (1).jpeg"))); // NOI18N
        Guayaquil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuayaquilActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel28.setText("Guayaquil -ECU");

        jLabel29.setText("USD");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("60");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Guayaquil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(Guayaquil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        VNacionales.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, 160));

        Quito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quito (1).jpg"))); // NOI18N
        Quito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitoActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel34.setText("Quito - ECU");

        jLabel35.setText("USD");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("60");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(Quito, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(Quito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        VNacionales.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 200, -1));

        Galapagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-884708080-612x612 (1).jpg"))); // NOI18N
        Galapagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalapagosActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel31.setText("Galápagos - ECU");

        jLabel32.setText("USD");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("200");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Galapagos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(Galapagos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(14, 14, 14))))
        );

        VNacionales.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 200, -1));

        Cuenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuenca (1).png"))); // NOI18N
        Cuenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuencaActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Nirmala Text", 1, 12)); // NOI18N
        jLabel37.setText("Cuencua - ECU");

        jLabel38.setText("USD");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("100");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(Cuenca, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(Cuenca, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        VNacionales.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 200, -1));

        grupo.add(VNacionales, "card5");

        Vuelos.setBackground(new java.awt.Color(0, 0, 102));
        Vuelos.setFocusable(false);
        Vuelos.setPreferredSize(new java.awt.Dimension(800, 500));
        Vuelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NGuayaquil.setText("Guayaquil");
        Vuelos.add(NGuayaquil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 42));

        ResG.setBackground(new java.awt.Color(255, 204, 0));
        ResG.setText("Detalles");
        ResG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResGActionPerformed(evt);
            }
        });
        Vuelos.add(ResG, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 80, 30));

        AreaGua.setEditable(false);
        AreaGua.setColumns(20);
        AreaGua.setRows(5);
        jScrollPane1.setViewportView(AreaGua);

        Vuelos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, 42));

        ResQ.setBackground(new java.awt.Color(255, 204, 0));
        ResQ.setText("Detalles");
        ResQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResQActionPerformed(evt);
            }
        });
        Vuelos.add(ResQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 62, 80, 30));

        AreaEs.setEditable(false);
        AreaEs.setColumns(20);
        AreaEs.setRows(5);
        jScrollPane2.setViewportView(AreaEs);

        Vuelos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 218, -1, 42));

        NQuito.setText("Quito");
        Vuelos.add(NQuito, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 62, 91, 42));

        NGalapagos.setText("Galapagos");
        Vuelos.add(NGalapagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 110, 91, 46));

        ResBra.setBackground(new java.awt.Color(255, 204, 0));
        ResBra.setText("Detalles");
        ResBra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResBraActionPerformed(evt);
            }
        });
        Vuelos.add(ResBra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 378, 80, 30));

        ResCu.setBackground(new java.awt.Color(255, 204, 0));
        ResCu.setText("Detalles");
        ResCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCuActionPerformed(evt);
            }
        });
        Vuelos.add(ResCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 162, 80, 30));

        ResEs.setBackground(new java.awt.Color(255, 204, 0));
        ResEs.setText("Detalles");
        ResEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResEsActionPerformed(evt);
            }
        });
        Vuelos.add(ResEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 218, 80, 30));

        ResEe.setBackground(new java.awt.Color(255, 204, 0));
        ResEe.setText("Detalles");
        ResEe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResEeActionPerformed(evt);
            }
        });
        Vuelos.add(ResEe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 80, 30));

        ResJa.setBackground(new java.awt.Color(255, 204, 0));
        ResJa.setText("Detalles");
        ResJa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResJaActionPerformed(evt);
            }
        });
        Vuelos.add(ResJa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 326, 80, 30));

        regresarVT.setText("Regresar");
        regresarVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarVTActionPerformed(evt);
            }
        });
        Vuelos.add(regresarVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        AreaCu.setEditable(false);
        AreaCu.setColumns(20);
        AreaCu.setRows(5);
        jScrollPane3.setViewportView(AreaCu);

        Vuelos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 162, -1, 46));

        AreaQui.setEditable(false);
        AreaQui.setColumns(20);
        AreaQui.setRows(5);
        jScrollPane4.setViewportView(AreaQui);

        Vuelos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 62, -1, 42));

        NCuenca.setText("Cuenca");
        Vuelos.add(NCuenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 162, 91, 46));

        IMadrid.setText("España");
        Vuelos.add(IMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 218, 91, 46));

        ILosAngeles.setText("EEUU");
        Vuelos.add(ILosAngeles, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 270, 91, 46));

        IJapon.setText("Japon");
        Vuelos.add(IJapon, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 322, 91, 46));

        Brasil.setText("Brasil");
        Vuelos.add(Brasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 374, 91, 46));

        AreaGa.setEditable(false);
        AreaGa.setColumns(20);
        AreaGa.setRows(5);
        jScrollPane5.setViewportView(AreaGa);

        Vuelos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 46));

        AreaBra.setEditable(false);
        AreaBra.setColumns(20);
        AreaBra.setRows(5);
        jScrollPane6.setViewportView(AreaBra);

        Vuelos.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 378, -1, 46));

        AreaJa.setEditable(false);
        AreaJa.setColumns(20);
        AreaJa.setRows(5);
        jScrollPane7.setViewportView(AreaJa);

        Vuelos.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 326, -1, 46));

        AreaEE.setEditable(false);
        AreaEE.setColumns(20);
        AreaEE.setRows(5);
        jScrollPane8.setViewportView(AreaEE);

        Vuelos.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 46));

        ResGa.setBackground(new java.awt.Color(255, 204, 0));
        ResGa.setText("Detalles");
        ResGa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResGaActionPerformed(evt);
            }
        });
        Vuelos.add(ResGa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, 30));
        Vuelos.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Elija su aventura");
        Vuelos.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avion10 (2).jpg"))); // NOI18N
        Vuelos.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 90, 80));

        grupo.add(Vuelos, "card3");

        BusquedaF.setBackground(new java.awt.Color(255, 255, 255));
        BusquedaF.setMinimumSize(new java.awt.Dimension(800, 500));
        BusquedaF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(0, 46, 140));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vuelo no encontrado...");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(57, 57, 57))
        );

        BusquedaF.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 540, 170));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/awa (1).jpg"))); // NOI18N
        jLabel47.setText("jLabel47");
        BusquedaF.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 270, 510));

        jButton12.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avioncitoPNG (1).png"))); // NOI18N
        jButton12.setText("   Busca más vuelos");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        BusquedaF.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triste (1).jpg"))); // NOI18N
        jLabel45.setText("jLabel45");
        BusquedaF.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 130, 114));

        grupo.add(BusquedaF, "card7");

        BusquedaE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarBE.setText("Regresar");
        regresarBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBEActionPerformed(evt);
            }
        });
        BusquedaE.add(regresarBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        TextoEncontrado.setEditable(false);
        TextoEncontrado.setColumns(20);
        TextoEncontrado.setRows(5);
        jScrollPane9.setViewportView(TextoEncontrado);

        BusquedaE.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 370, 240));

        ReservarBE.setBackground(new java.awt.Color(255, 204, 0));
        ReservarBE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReservarBE.setText("Reservar");
        ReservarBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBEActionPerformed(evt);
            }
        });
        BusquedaE.add(ReservarBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 46, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalles del vuelo");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        BusquedaE.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        grupo.add(BusquedaE, "card8");

        Reservar.setBackground(new java.awt.Color(204, 204, 204));
        Reservar.setPreferredSize(new java.awt.Dimension(800, 500));
        Reservar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Reservar.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 395, -1));
        Reservar.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 395, -1));

        jLabel5.setText("Ingrese su cedula de identidad");
        Reservar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 177, -1));
        Reservar.add(Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 395, -1));

        jLabel6.setText("Ingrese su nacionalidad");
        Reservar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 177, -1));

        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro", "Prefiero no decirlo" }));
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });
        Reservar.add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 395, -1));

        jLabel7.setText("Ingrese su genero");
        Reservar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 177, -1));
        Reservar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel41.setText("Ingrese su nombre:");
        Reservar.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 46, 140));

        ReservarRegresar.setText("Regresar");
        ReservarRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarRegresarActionPerformed(evt);
            }
        });

        ReservarConfirmar.setText("Confirmar");
        ReservarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(ReservarRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                .addComponent(ReservarConfirmar)
                .addGap(97, 97, 97))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservarRegresar)
                    .addComponent(ReservarConfirmar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Reservar.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 800, -1));

        grupo.add(Reservar, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        // TODO add your handling code here:
        AreaGua.setText(an.getVuelo().get(0).getDatos());
        AreaQui.setText(an.getVuelo().get(0).getDatos());
        AreaGa.setText(an.getVuelo().get(0).getDatos());
        AreaCu.setText(an.getVuelo().get(0).getDatos());
        AreaEs.setText(ai.getVuelo().get(0).getDatos());
        AreaEE.setText(ai.getVuelo().get(0).getDatos());
        AreaJa.setText(ai.getVuelo().get(0).getDatos());
        AreaBra.setText(ai.getVuelo().get(0).getDatos());
        CambiarPanel(Vuelos);
        
    }//GEN-LAST:event_todosActionPerformed

    private void nacionalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalBActionPerformed
        // TODO add your handling code here:
        CambiarPanel(VNacionales);
    }//GEN-LAST:event_nacionalBActionPerformed

    private void internacionalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internacionalBActionPerformed
        // TODO add your handling code here:
        CambiarPanel(VInternacionales);
    }//GEN-LAST:event_internacionalBActionPerformed

    private void buscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTActionPerformed

    private void VerBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerBoletoActionPerformed
        // TODO add your handling code here:
        if (bolea==false)
            BoletoVer.setText("Sin boletos adquiridos");
        CambiarPanel(Boleto);
    }//GEN-LAST:event_VerBoletoActionPerformed

    private void MadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MadridActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(0).getDatos());
        buscarT.setText(ai.getVuelo().get(0).getDestino());
    }//GEN-LAST:event_MadridActionPerformed

    private void RegresarVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarVIActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Menu);
    }//GEN-LAST:event_RegresarVIActionPerformed

    private void regresarVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarVNActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Menu);
    }//GEN-LAST:event_regresarVNActionPerformed

    private void regresarVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarVTActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Menu);
    }//GEN-LAST:event_regresarVTActionPerformed

    private void regresarBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBEActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Menu);
    }//GEN-LAST:event_regresarBEActionPerformed

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        // TODO add your handling code here:       
        boolean encontrado=false;
        
        for(int i=0;i<an.getVuelo().size();i++){        
            if(an.getVuelo().get(i).getDestino().equals(buscarT.getText())){
               encontrado=true;
               TextoEncontrado.setText(an.getVuelo().get(i).getDatos());
               CambiarPanel(BusquedaE);               
               break;
            }            
        }
        if(!encontrado){
           for(int i=0;i<ai.getVuelo().size();i++){        
            if(ai.getVuelo().get(i).getDestino().equals(buscarT.getText())){          
               TextoEncontrado.setText(ai.getVuelo().get(i).getDatos());
               CambiarPanel(BusquedaE);
               break;
            }
            else
               CambiarPanel(BusquedaF);
        }           
        }
    }//GEN-LAST:event_buscarBActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Menu);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActionPerformed

    private void ReservarBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBEActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Reservar);
    }//GEN-LAST:event_ReservarBEActionPerformed

    private void ReservarRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarRegresarActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
    }//GEN-LAST:event_ReservarRegresarActionPerformed

    private void ReservarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarConfirmarActionPerformed
        // TODO add your handling code here:
        bolea=true;
        boolean encontrado=false;        
        Pasajero pas=new Pasajero(Nombre.getText(),ID.getText(),Nacionalidad.getText(),Genero.getSelectedItem().toString());
        for(int i=0;i<an.getVuelo().size();i++){        
            if(an.getVuelo().get(i).getDestino().equals(buscarT.getText())){
               encontrado=true;               
               pas.ComprarBoleto(an.getVuelo().get(i).getTipoVuelo(), an.getVuelo().get(i).getPrecio(),  an.getVuelo().get(i).getFechaSalida(), an.getVuelo().get(i).getFechaRegreso(),an.getVuelo().get(i).getCodigoVuelo(),an.getVuelo().get(i).getDestino(),an.getVuelo().get(i).getOrigen(),2);
               BoletoVer.setText(pas.VerVuelo());
               CambiarPanel(Boleto);           
               buscarT.setText("");
               break;
            }            
        }
        if(!encontrado){
           for(int i=0;i<ai.getVuelo().size();i++){        
            if(ai.getVuelo().get(i).getDestino().equals(buscarT.getText())){  
               pas.ComprarBoleto(ai.getVuelo().get(i).getTipoVuelo(), ai.getVuelo().get(i).getPrecio(),  ai.getVuelo().get(i).getFechaSalida(), ai.getVuelo().get(i).getFechaRegreso(),ai.getVuelo().get(i).getCodigoVuelo(),ai.getVuelo().get(i).getDestino(),ai.getVuelo().get(i).getOrigen(),2);
               BoletoVer.setText(pas.VerVuelo());
               CambiarPanel(Boleto);
               buscarT.setText("");
               break;
            }         
        }         
     }
     CambiarPanel(Boleto);
    }//GEN-LAST:event_ReservarConfirmarActionPerformed

    private void BoletoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoletoMenuActionPerformed
        // TODO add your handling code here:
        CambiarPanel(Menu);
    }//GEN-LAST:event_BoletoMenuActionPerformed

    private void GuayaquilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuayaquilActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(0).getDatos());
        buscarT.setText(an.getVuelo().get(0).getDestino());
    }//GEN-LAST:event_GuayaquilActionPerformed

    private void QuitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitoActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(1).getDatos());
        buscarT.setText(an.getVuelo().get(1).getDestino());
    }//GEN-LAST:event_QuitoActionPerformed

    private void GalapagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalapagosActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(2).getDatos());
        buscarT.setText(an.getVuelo().get(2).getDestino());
    }//GEN-LAST:event_GalapagosActionPerformed

    private void CuencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuencaActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(3).getDatos());
        buscarT.setText(an.getVuelo().get(3).getDestino());
    }//GEN-LAST:event_CuencaActionPerformed

    private void LosAngelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LosAngelesActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(1).getDatos());
        buscarT.setText(ai.getVuelo().get(1).getDestino());
    }//GEN-LAST:event_LosAngelesActionPerformed

    private void TokyioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokyioActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(2).getDatos());
        buscarT.setText(ai.getVuelo().get(2).getDestino());
    }//GEN-LAST:event_TokyioActionPerformed

    private void ResGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResGActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(0).getDatos());
        buscarT.setText(an.getVuelo().get(0).getDestino());
    }//GEN-LAST:event_ResGActionPerformed

    private void ResQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResQActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(1).getDatos());
        buscarT.setText(an.getVuelo().get(1).getDestino());
    }//GEN-LAST:event_ResQActionPerformed

    private void ResGaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResGaActionPerformed
        // TODO add your handling code here:
          CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(2).getDatos());
        buscarT.setText(an.getVuelo().get(2).getDestino());
    }//GEN-LAST:event_ResGaActionPerformed

    private void ResCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCuActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(an.getVuelo().get(3).getDatos());
        buscarT.setText(an.getVuelo().get(3).getDestino());
    }//GEN-LAST:event_ResCuActionPerformed

    private void ResEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResEsActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(0).getDatos());
        buscarT.setText(ai.getVuelo().get(0).getDestino());
    }//GEN-LAST:event_ResEsActionPerformed

    private void ResEeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResEeActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(1).getDatos());
        buscarT.setText(ai.getVuelo().get(1).getDestino());
    }//GEN-LAST:event_ResEeActionPerformed

    private void ResJaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResJaActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(2).getDatos());
        buscarT.setText(ai.getVuelo().get(2).getDestino());
    }//GEN-LAST:event_ResJaActionPerformed

    private void ResBraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResBraActionPerformed
        // TODO add your handling code here:
         CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(3).getDatos());
        buscarT.setText(ai.getVuelo().get(3).getDestino());
    }//GEN-LAST:event_ResBraActionPerformed

    private void RioDeJaneiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RioDeJaneiroActionPerformed
        // TODO add your handling code here:
        CambiarPanel(BusquedaE);
        TextoEncontrado.setText(ai.getVuelo().get(3).getDatos());
        buscarT.setText(ai.getVuelo().get(3).getDestino());
    }//GEN-LAST:event_RioDeJaneiroActionPerformed

    /**
     * @param args the command line arguments
     */
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaBra;
    private javax.swing.JTextArea AreaCu;
    private javax.swing.JTextArea AreaEE;
    private javax.swing.JTextArea AreaEs;
    private javax.swing.JTextArea AreaGa;
    private javax.swing.JTextArea AreaGua;
    private javax.swing.JTextArea AreaJa;
    private javax.swing.JTextArea AreaQui;
    private javax.swing.JPanel Boleto;
    private javax.swing.JButton BoletoMenu;
    private javax.swing.JTextArea BoletoVer;
    private javax.swing.JButton Brasil;
    private javax.swing.JPanel BusquedaE;
    private javax.swing.JPanel BusquedaF;
    private javax.swing.JButton Cuenca;
    private javax.swing.JButton Galapagos;
    private javax.swing.JComboBox<String> Genero;
    private javax.swing.JButton Guayaquil;
    private javax.swing.JTextField ID;
    private javax.swing.JButton IJapon;
    private javax.swing.JButton ILosAngeles;
    private javax.swing.JButton IMadrid;
    private javax.swing.JButton LosAngeles;
    private javax.swing.JButton Madrid;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton NCuenca;
    private javax.swing.JButton NGalapagos;
    private javax.swing.JButton NGuayaquil;
    private javax.swing.JButton NQuito;
    private javax.swing.JTextField Nacionalidad;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Quito;
    private javax.swing.JButton RegresarVI;
    private javax.swing.JButton ResBra;
    private javax.swing.JButton ResCu;
    private javax.swing.JButton ResEe;
    private javax.swing.JButton ResEs;
    private javax.swing.JButton ResG;
    private javax.swing.JButton ResGa;
    private javax.swing.JButton ResJa;
    private javax.swing.JButton ResQ;
    private javax.swing.JPanel Reservar;
    private javax.swing.JButton ReservarBE;
    private javax.swing.JButton ReservarConfirmar;
    private javax.swing.JButton ReservarRegresar;
    private javax.swing.JButton RioDeJaneiro;
    private javax.swing.JTextArea TextoEncontrado;
    private javax.swing.JButton Tokyio;
    private javax.swing.JPanel VInternacionales;
    private javax.swing.JPanel VNacionales;
    private javax.swing.JButton VerBoleto;
    private javax.swing.JPanel Vuelos;
    private javax.swing.JButton buscarB;
    private javax.swing.JTextField buscarT;
    private javax.swing.JLayeredPane grupo;
    private javax.swing.JButton internacionalB;
    private javax.swing.JButton jButton12;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton nacionalB;
    private javax.swing.JButton regresarBE;
    private javax.swing.JButton regresarVN;
    private javax.swing.JButton regresarVT;
    private javax.swing.JButton todos;
    // End of variables declaration//GEN-END:variables
}
